# variable =True


# if variable :
#     print("look the message")
# else:
#     print("my variable is False")


# message = input ('¿Cuantos años tiene? ')
# message= int(message)


# age = 18

# if age > 18:
#     print("Entra a la disco")
# else:
#     print("No entra a la disco")



fast_food = ["pizza"]

if fast_food[0]=="pizza":
    print("Yuuuuhuuuu")

else:
    print("Ocuhhhhhhhhh!!!")